#From https://github.com/ProjectHDS/Herodotus/blob/master/.github/workflows/dev.yml

# This is a basic workflow to help you get started with Actions

name: dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
    # Runs a single command using the runners shell
      - name: Run build.sh
        run: bash build.sh
    #Upload the artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
        # Artifact name
          name: Herodotus-dev
        # A file, directory or wildcard pattern that describes what to upload
          path: artifacts